<?php
$DATABASE_LINK="127.0.0.1";
$DATABASE_USERNAME="root";
$DATABASE_PASSWORD="root";
$DATABASE_NAME="dict";

define("LINK",$DATABASE_LINK);
define("USERNAME",$DATABASE_USERNAME);
define("PASSWORD",$DATABASE_PASSWORD);
define("NAME",$DATABASE_NAME);